//=====================================================================
//  Autogenerated at 05/28/2013 16:44:27
//  NI WSN-3202
//  Copyright National Instruments.  All Rights Reserved.
//=====================================================================


//=====================================================================
//  Includes and Defines
//=====================================================================
#include "firmware.h"

typedef enum IOVAttr_enum {
IOVAttr_Big = 1 << 0,
IOVAttr_ExtRam = 1 << 1,
IOVAttr_Input = 1 << 2,
IOVAttr_Output = 1 << 3,
IOVAttr_RelaxedTimestamp = 1 << 4,
IOVAttr_Passthrough = 1 << 5,
IOVAttr_Waveform = 1 << 6,
IOVAttr_String = 1 << 7
} IOVAttr;

#if defined(__cplusplus)
    #define EXTERN extern "C"
#else
    #define EXTERN
#endif

//=====================================================================
//  Describe the channels
//=====================================================================


//NOTE: in process of migrating from viotn prefix to lvwsn prefix
//      NI WSN will migrate at some future point and deprecate viotn.
//      Meanwhile, all symbols for LV WSN are duplicated with lvwsn prefix.
EXTERN const u8 viotn_iovNumChannels = 19;
EXTERN const u8 lvwsn_iovNumChannels = 19;
EXTERN const ChannelSize viotn_iovChannelSize[] = {0x0004, 0x0004, 0x0004, 0x0004, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0004, 0x0004, 0x0004, 0x0004, 0x0001, 0x0001, 0x0001};
EXTERN const ChannelSize lvwsn_iovChannelSize[] = {0x0004, 0x0004, 0x0004, 0x0004, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0004, 0x0004, 0x0004, 0x0004, 0x0001, 0x0001, 0x0001};
EXTERN const u8 viotn_iovChannelDepth[] = {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2};
EXTERN const u8 lvwsn_iovChannelDepth[] = {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2};
EXTERN const u8 viotn_iovChannelAttrs[] = {
    /* AI0                       */ IOVAttr_Input,
    /* AI1                       */ IOVAttr_Input,
    /* AI2                       */ IOVAttr_Input,
    /* AI3                       */ IOVAttr_Input,
    /* __config__DI0             */ IOVAttr_Input,
    /* __config__DI1             */ IOVAttr_Input,
    /* __config__DI2             */ IOVAttr_Input,
    /* __config__DI3             */ IOVAttr_Input,
    /* DIO0                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO1                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO2                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO3                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* __config__Sample Interval */ IOVAttr_Output | IOVAttr_RelaxedTimestamp | IOVAttr_Passthrough,
    /* __config__Heartbeat       */ IOVAttr_Output | IOVAttr_RelaxedTimestamp | IOVAttr_Passthrough,
    /* Battery Voltage           */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* Link Quality              */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* VI Deployed               */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* External Power            */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* Mesh Router               */ IOVAttr_Input | IOVAttr_RelaxedTimestamp
};
EXTERN const u8 lvwsn_iovChannelAttrs[] = {
    /* AI0                       */ IOVAttr_Input,
    /* AI1                       */ IOVAttr_Input,
    /* AI2                       */ IOVAttr_Input,
    /* AI3                       */ IOVAttr_Input,
    /* __config__DI0             */ IOVAttr_Input,
    /* __config__DI1             */ IOVAttr_Input,
    /* __config__DI2             */ IOVAttr_Input,
    /* __config__DI3             */ IOVAttr_Input,
    /* DIO0                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO1                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO2                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO3                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* __config__Sample Interval */ IOVAttr_Output | IOVAttr_RelaxedTimestamp | IOVAttr_Passthrough,
    /* __config__Heartbeat       */ IOVAttr_Output | IOVAttr_RelaxedTimestamp | IOVAttr_Passthrough,
    /* Battery Voltage           */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* Link Quality              */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* VI Deployed               */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* External Power            */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* Mesh Router               */ IOVAttr_Input | IOVAttr_RelaxedTimestamp
};
EXTERN const char* const viotn_iovChannelDescriptor[] = {"d", "d", "d", "d", "a", "a", "a", "a", "a", "a", "a", "a", "d", "d", "d", "d", "a", "a", "a"};
EXTERN const char* const lvwsn_iovChannelDescriptor[] = {"d", "d", "d", "d", "a", "a", "a", "a", "a", "a", "a", "a", "d", "d", "d", "d", "a", "a", "a"};


EXTERN const u8 lvwsn_iovChannelCoreTypes[] = {
    IOVCoreType_f32,
    IOVCoreType_f32,
    IOVCoreType_f32,
    IOVCoreType_f32,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_f32,
    IOVCoreType_f32,
    IOVCoreType_f32,
    IOVCoreType_f32,
    IOVCoreType_bool,
    IOVCoreType_bool,
    IOVCoreType_bool
};

EXTERN const char* const lvwsn_iovChannelName[] = {
    "AI0",
    "AI1",
    "AI2",
    "AI3",
    "__config__DI0",
    "__config__DI1",
    "__config__DI2",
    "__config__DI3",
    "DIO0",
    "DIO1",
    "DIO2",
    "DIO3",
    "__config__Sample Interval",
    "__config__Heartbeat",
    "Battery Voltage",
    "Link Quality",
    "VI Deployed",
    "External Power",
    "Mesh Router"
};



//=====================================================================
//  Declare the timestamp FIFOs
//=====================================================================
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_0_lo[2];
#define viotn_iovTimeStamp_0_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_1_lo[2];
#define viotn_iovTimeStamp_1_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_2_lo[2];
#define viotn_iovTimeStamp_2_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_3_lo[2];
#define viotn_iovTimeStamp_3_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_4_lo[2];
#define viotn_iovTimeStamp_4_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_5_lo[2];
#define viotn_iovTimeStamp_5_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_6_lo[2];
#define viotn_iovTimeStamp_6_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_7_lo[2];
#define viotn_iovTimeStamp_7_hi 0
#define viotn_iovTimeStamp_8_lo 0
#define viotn_iovTimeStamp_8_hi 0
#define viotn_iovTimeStamp_9_lo 0
#define viotn_iovTimeStamp_9_hi 0
#define viotn_iovTimeStamp_10_lo 0
#define viotn_iovTimeStamp_10_hi 0
#define viotn_iovTimeStamp_11_lo 0
#define viotn_iovTimeStamp_11_hi 0
#define viotn_iovTimeStamp_12_lo 0
#define viotn_iovTimeStamp_12_hi 0
#define viotn_iovTimeStamp_13_lo 0
#define viotn_iovTimeStamp_13_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_14_lo[2];
#define viotn_iovTimeStamp_14_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_15_lo[2];
#define viotn_iovTimeStamp_15_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_16_lo[2];
#define viotn_iovTimeStamp_16_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_17_lo[2];
#define viotn_iovTimeStamp_17_hi 0
#pragma DATA_SECTION(".lvbss")
static TimeStamp viotn_iovTimeStamp_18_lo[2];
#define viotn_iovTimeStamp_18_hi 0

EXTERN const u16 viotn_iovTimeStampFifo[] = {
    (u16)viotn_iovTimeStamp_0_lo, (u16)viotn_iovTimeStamp_0_hi,
    (u16)viotn_iovTimeStamp_1_lo, (u16)viotn_iovTimeStamp_1_hi,
    (u16)viotn_iovTimeStamp_2_lo, (u16)viotn_iovTimeStamp_2_hi,
    (u16)viotn_iovTimeStamp_3_lo, (u16)viotn_iovTimeStamp_3_hi,
    (u16)viotn_iovTimeStamp_4_lo, (u16)viotn_iovTimeStamp_4_hi,
    (u16)viotn_iovTimeStamp_5_lo, (u16)viotn_iovTimeStamp_5_hi,
    (u16)viotn_iovTimeStamp_6_lo, (u16)viotn_iovTimeStamp_6_hi,
    (u16)viotn_iovTimeStamp_7_lo, (u16)viotn_iovTimeStamp_7_hi,
    (u16)viotn_iovTimeStamp_8_lo, (u16)viotn_iovTimeStamp_8_hi,
    (u16)viotn_iovTimeStamp_9_lo, (u16)viotn_iovTimeStamp_9_hi,
    (u16)viotn_iovTimeStamp_10_lo, (u16)viotn_iovTimeStamp_10_hi,
    (u16)viotn_iovTimeStamp_11_lo, (u16)viotn_iovTimeStamp_11_hi,
    (u16)viotn_iovTimeStamp_12_lo, (u16)viotn_iovTimeStamp_12_hi,
    (u16)viotn_iovTimeStamp_13_lo, (u16)viotn_iovTimeStamp_13_hi,
    (u16)viotn_iovTimeStamp_14_lo, (u16)viotn_iovTimeStamp_14_hi,
    (u16)viotn_iovTimeStamp_15_lo, (u16)viotn_iovTimeStamp_15_hi,
    (u16)viotn_iovTimeStamp_16_lo, (u16)viotn_iovTimeStamp_16_hi,
    (u16)viotn_iovTimeStamp_17_lo, (u16)viotn_iovTimeStamp_17_hi,
    (u16)viotn_iovTimeStamp_18_lo, (u16)viotn_iovTimeStamp_18_hi
};


EXTERN const u16 lvwsn_iovTimeStampFifo[] = {
    (u16)viotn_iovTimeStamp_0_lo, (u16)viotn_iovTimeStamp_0_hi,
    (u16)viotn_iovTimeStamp_1_lo, (u16)viotn_iovTimeStamp_1_hi,
    (u16)viotn_iovTimeStamp_2_lo, (u16)viotn_iovTimeStamp_2_hi,
    (u16)viotn_iovTimeStamp_3_lo, (u16)viotn_iovTimeStamp_3_hi,
    (u16)viotn_iovTimeStamp_4_lo, (u16)viotn_iovTimeStamp_4_hi,
    (u16)viotn_iovTimeStamp_5_lo, (u16)viotn_iovTimeStamp_5_hi,
    (u16)viotn_iovTimeStamp_6_lo, (u16)viotn_iovTimeStamp_6_hi,
    (u16)viotn_iovTimeStamp_7_lo, (u16)viotn_iovTimeStamp_7_hi,
    (u16)viotn_iovTimeStamp_8_lo, (u16)viotn_iovTimeStamp_8_hi,
    (u16)viotn_iovTimeStamp_9_lo, (u16)viotn_iovTimeStamp_9_hi,
    (u16)viotn_iovTimeStamp_10_lo, (u16)viotn_iovTimeStamp_10_hi,
    (u16)viotn_iovTimeStamp_11_lo, (u16)viotn_iovTimeStamp_11_hi,
    (u16)viotn_iovTimeStamp_12_lo, (u16)viotn_iovTimeStamp_12_hi,
    (u16)viotn_iovTimeStamp_13_lo, (u16)viotn_iovTimeStamp_13_hi,
    (u16)viotn_iovTimeStamp_14_lo, (u16)viotn_iovTimeStamp_14_hi,
    (u16)viotn_iovTimeStamp_15_lo, (u16)viotn_iovTimeStamp_15_hi,
    (u16)viotn_iovTimeStamp_16_lo, (u16)viotn_iovTimeStamp_16_hi,
    (u16)viotn_iovTimeStamp_17_lo, (u16)viotn_iovTimeStamp_17_hi,
    (u16)viotn_iovTimeStamp_18_lo, (u16)viotn_iovTimeStamp_18_hi
};



//=====================================================================
//  Declare the data FIFOs
//=====================================================================
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_0_lo[2];
#define viotn_iovData_0_hi 0
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_1_lo[2];
#define viotn_iovData_1_hi 0
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_2_lo[2];
#define viotn_iovData_2_hi 0
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_3_lo[2];
#define viotn_iovData_3_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_4_lo[2];
#define viotn_iovData_4_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_5_lo[2];
#define viotn_iovData_5_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_6_lo[2];
#define viotn_iovData_6_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_7_lo[2];
#define viotn_iovData_7_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_8_lo[2];
#define viotn_iovData_8_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_9_lo[2];
#define viotn_iovData_9_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_10_lo[2];
#define viotn_iovData_10_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_11_lo[2];
#define viotn_iovData_11_hi 0
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_12_lo[1];
#define viotn_iovData_12_hi 0
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_13_lo[1];
#define viotn_iovData_13_hi 0
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_14_lo[2];
#define viotn_iovData_14_hi 0
#pragma DATA_SECTION(".lvbss")
static f32 viotn_iovData_15_lo[2];
#define viotn_iovData_15_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_16_lo[2];
#define viotn_iovData_16_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_17_lo[2];
#define viotn_iovData_17_hi 0
#pragma DATA_SECTION(".lvbss")
static u8 viotn_iovData_18_lo[2];
#define viotn_iovData_18_hi 0

EXTERN const u16 viotn_iovDataFifo[] = {
    (u16)viotn_iovData_0_lo, (u16)viotn_iovData_0_hi,
    (u16)viotn_iovData_1_lo, (u16)viotn_iovData_1_hi,
    (u16)viotn_iovData_2_lo, (u16)viotn_iovData_2_hi,
    (u16)viotn_iovData_3_lo, (u16)viotn_iovData_3_hi,
    (u16)viotn_iovData_4_lo, (u16)viotn_iovData_4_hi,
    (u16)viotn_iovData_5_lo, (u16)viotn_iovData_5_hi,
    (u16)viotn_iovData_6_lo, (u16)viotn_iovData_6_hi,
    (u16)viotn_iovData_7_lo, (u16)viotn_iovData_7_hi,
    (u16)viotn_iovData_8_lo, (u16)viotn_iovData_8_hi,
    (u16)viotn_iovData_9_lo, (u16)viotn_iovData_9_hi,
    (u16)viotn_iovData_10_lo, (u16)viotn_iovData_10_hi,
    (u16)viotn_iovData_11_lo, (u16)viotn_iovData_11_hi,
    (u16)viotn_iovData_12_lo, (u16)viotn_iovData_12_hi,
    (u16)viotn_iovData_13_lo, (u16)viotn_iovData_13_hi,
    (u16)viotn_iovData_14_lo, (u16)viotn_iovData_14_hi,
    (u16)viotn_iovData_15_lo, (u16)viotn_iovData_15_hi,
    (u16)viotn_iovData_16_lo, (u16)viotn_iovData_16_hi,
    (u16)viotn_iovData_17_lo, (u16)viotn_iovData_17_hi,
    (u16)viotn_iovData_18_lo, (u16)viotn_iovData_18_hi
};


EXTERN const u16 lvwsn_iovDataFifo[] = {
    (u16)viotn_iovData_0_lo, (u16)viotn_iovData_0_hi,
    (u16)viotn_iovData_1_lo, (u16)viotn_iovData_1_hi,
    (u16)viotn_iovData_2_lo, (u16)viotn_iovData_2_hi,
    (u16)viotn_iovData_3_lo, (u16)viotn_iovData_3_hi,
    (u16)viotn_iovData_4_lo, (u16)viotn_iovData_4_hi,
    (u16)viotn_iovData_5_lo, (u16)viotn_iovData_5_hi,
    (u16)viotn_iovData_6_lo, (u16)viotn_iovData_6_hi,
    (u16)viotn_iovData_7_lo, (u16)viotn_iovData_7_hi,
    (u16)viotn_iovData_8_lo, (u16)viotn_iovData_8_hi,
    (u16)viotn_iovData_9_lo, (u16)viotn_iovData_9_hi,
    (u16)viotn_iovData_10_lo, (u16)viotn_iovData_10_hi,
    (u16)viotn_iovData_11_lo, (u16)viotn_iovData_11_hi,
    (u16)viotn_iovData_12_lo, (u16)viotn_iovData_12_hi,
    (u16)viotn_iovData_13_lo, (u16)viotn_iovData_13_hi,
    (u16)viotn_iovData_14_lo, (u16)viotn_iovData_14_hi,
    (u16)viotn_iovData_15_lo, (u16)viotn_iovData_15_hi,
    (u16)viotn_iovData_16_lo, (u16)viotn_iovData_16_hi,
    (u16)viotn_iovData_17_lo, (u16)viotn_iovData_17_hi,
    (u16)viotn_iovData_18_lo, (u16)viotn_iovData_18_hi
};



//=====================================================================
//  Declare the output tokens information
//=====================================================================
EXTERN const u8 viotn_iovTokenArraySize = 0;

EXTERN const u8 lvwsn_iovTokenArraySize = 0;

#define viotn_iovLatchedTokenArray_lo ((u8*)0)
#define viotn_iovAccumTokenArray_lo ((u8*)0)
EXTERN u8* const viotn_iovLatchedTokenArray = viotn_iovLatchedTokenArray_lo;
EXTERN u8* const lvwsn_iovLatchedTokenArray = viotn_iovLatchedTokenArray_lo;
EXTERN u8* const viotn_iovAccumTokenArray = viotn_iovAccumTokenArray_lo;
EXTERN u8* const lvwsn_iovAccumTokenArray = viotn_iovAccumTokenArray_lo;

EXTERN const u8 viotn_iovTokenIndexArray[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
EXTERN const u8 lvwsn_iovTokenIndexArray[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

