//---------------------------------------------------------------
//  Autogenerated at 05/28/2013 16:44:27
//  NI WSN-3202
//  External RAM area accessible to LV WSN memory allocation
//  Copyright National Instruments.  All Rights Reserved.
//---------------------------------------------------------------
#define LVWSN_EXTRAM_START    0x80000000
#define LVWSN_EXTRAM_LENGTH   0x00000000
