//=====================================================================
//  Autogenerated at 05/28/2013 16:44:28
//  NI WSN-3202
//  Copyright National Instruments.  All Rights Reserved.
//=====================================================================


//=====================================================================
//  Includes and Defines
//=====================================================================
#include "Common.h"
#define DECLARING_IOV_FIFOS
#include "Channels.h"

#if defined(__cplusplus)
    #define EXTERN extern "C"
#else
    #define EXTERN
#endif

//=====================================================================
//  Describe the channels
//=====================================================================
EXTERN const u8 niwsn_iovNumChannels = 19;
EXTERN const ChannelSize niwsn_iovChannelSize[] = {0x0004, 0x0004, 0x0004, 0x0004, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0004, 0x0004, 0x0004, 0x0004, 0x0001, 0x0001, 0x0001};
EXTERN const u8 niwsn_iovChannelDepth[] = {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2};
EXTERN const u8 niwsn_iovChannelAttrs[] = {
    /* AI0                       */ IOVAttr_Input,
    /* AI1                       */ IOVAttr_Input,
    /* AI2                       */ IOVAttr_Input,
    /* AI3                       */ IOVAttr_Input,
    /* __config__DI0             */ IOVAttr_Input,
    /* __config__DI1             */ IOVAttr_Input,
    /* __config__DI2             */ IOVAttr_Input,
    /* __config__DI3             */ IOVAttr_Input,
    /* DIO0                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO1                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO2                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* DIO3                      */ IOVAttr_Output | IOVAttr_Passthrough,
    /* __config__Sample Interval */ IOVAttr_Output | IOVAttr_RelaxedTimestamp | IOVAttr_Passthrough,
    /* __config__Heartbeat       */ IOVAttr_Output | IOVAttr_RelaxedTimestamp | IOVAttr_Passthrough,
    /* Battery Voltage           */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* Link Quality              */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* VI Deployed               */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* External Power            */ IOVAttr_Input | IOVAttr_RelaxedTimestamp,
    /* Mesh Router               */ IOVAttr_Input | IOVAttr_RelaxedTimestamp
};
EXTERN const char* const niwsn_iovChannelDescriptor[] = {"d", "d", "d", "d", "a", "a", "a", "a", "a", "a", "a", "a", "d", "d", "d", "d", "a", "a", "a"};


//=====================================================================
//  Declare the timestamp FIFOs
//=====================================================================
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_0_lo[2];
#define niwsn_iovTimeStamp_0_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_1_lo[2];
#define niwsn_iovTimeStamp_1_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_2_lo[2];
#define niwsn_iovTimeStamp_2_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_3_lo[2];
#define niwsn_iovTimeStamp_3_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_4_lo[2];
#define niwsn_iovTimeStamp_4_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_5_lo[2];
#define niwsn_iovTimeStamp_5_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_6_lo[2];
#define niwsn_iovTimeStamp_6_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_7_lo[2];
#define niwsn_iovTimeStamp_7_hi 0
#define niwsn_iovTimeStamp_8_lo 0
#define niwsn_iovTimeStamp_8_hi 0
#define niwsn_iovTimeStamp_9_lo 0
#define niwsn_iovTimeStamp_9_hi 0
#define niwsn_iovTimeStamp_10_lo 0
#define niwsn_iovTimeStamp_10_hi 0
#define niwsn_iovTimeStamp_11_lo 0
#define niwsn_iovTimeStamp_11_hi 0
#define niwsn_iovTimeStamp_12_lo 0
#define niwsn_iovTimeStamp_12_hi 0
#define niwsn_iovTimeStamp_13_lo 0
#define niwsn_iovTimeStamp_13_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_14_lo[2];
#define niwsn_iovTimeStamp_14_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_15_lo[2];
#define niwsn_iovTimeStamp_15_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_16_lo[2];
#define niwsn_iovTimeStamp_16_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_17_lo[2];
#define niwsn_iovTimeStamp_17_hi 0
#pragma DATA_SECTION(".niwsn")
static TimeStamp niwsn_iovTimeStamp_18_lo[2];
#define niwsn_iovTimeStamp_18_hi 0

EXTERN const u16 niwsn_iovTimeStampFifo[] = {
    (u16)niwsn_iovTimeStamp_0_lo, (u16)niwsn_iovTimeStamp_0_hi,
    (u16)niwsn_iovTimeStamp_1_lo, (u16)niwsn_iovTimeStamp_1_hi,
    (u16)niwsn_iovTimeStamp_2_lo, (u16)niwsn_iovTimeStamp_2_hi,
    (u16)niwsn_iovTimeStamp_3_lo, (u16)niwsn_iovTimeStamp_3_hi,
    (u16)niwsn_iovTimeStamp_4_lo, (u16)niwsn_iovTimeStamp_4_hi,
    (u16)niwsn_iovTimeStamp_5_lo, (u16)niwsn_iovTimeStamp_5_hi,
    (u16)niwsn_iovTimeStamp_6_lo, (u16)niwsn_iovTimeStamp_6_hi,
    (u16)niwsn_iovTimeStamp_7_lo, (u16)niwsn_iovTimeStamp_7_hi,
    (u16)niwsn_iovTimeStamp_8_lo, (u16)niwsn_iovTimeStamp_8_hi,
    (u16)niwsn_iovTimeStamp_9_lo, (u16)niwsn_iovTimeStamp_9_hi,
    (u16)niwsn_iovTimeStamp_10_lo, (u16)niwsn_iovTimeStamp_10_hi,
    (u16)niwsn_iovTimeStamp_11_lo, (u16)niwsn_iovTimeStamp_11_hi,
    (u16)niwsn_iovTimeStamp_12_lo, (u16)niwsn_iovTimeStamp_12_hi,
    (u16)niwsn_iovTimeStamp_13_lo, (u16)niwsn_iovTimeStamp_13_hi,
    (u16)niwsn_iovTimeStamp_14_lo, (u16)niwsn_iovTimeStamp_14_hi,
    (u16)niwsn_iovTimeStamp_15_lo, (u16)niwsn_iovTimeStamp_15_hi,
    (u16)niwsn_iovTimeStamp_16_lo, (u16)niwsn_iovTimeStamp_16_hi,
    (u16)niwsn_iovTimeStamp_17_lo, (u16)niwsn_iovTimeStamp_17_hi,
    (u16)niwsn_iovTimeStamp_18_lo, (u16)niwsn_iovTimeStamp_18_hi
};



//=====================================================================
//  Declare the data FIFOs
//=====================================================================
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_0_lo[2];
#define niwsn_iovData_0_hi 0
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_1_lo[2];
#define niwsn_iovData_1_hi 0
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_2_lo[2];
#define niwsn_iovData_2_hi 0
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_3_lo[2];
#define niwsn_iovData_3_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_4_lo[2];
#define niwsn_iovData_4_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_5_lo[2];
#define niwsn_iovData_5_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_6_lo[2];
#define niwsn_iovData_6_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_7_lo[2];
#define niwsn_iovData_7_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_8_lo[2];
#define niwsn_iovData_8_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_9_lo[2];
#define niwsn_iovData_9_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_10_lo[2];
#define niwsn_iovData_10_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_11_lo[2];
#define niwsn_iovData_11_hi 0
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_12_lo[1];
#define niwsn_iovData_12_hi 0
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_13_lo[1];
#define niwsn_iovData_13_hi 0
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_14_lo[2];
#define niwsn_iovData_14_hi 0
#pragma DATA_SECTION(".niwsn")
static f32 niwsn_iovData_15_lo[2];
#define niwsn_iovData_15_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_16_lo[2];
#define niwsn_iovData_16_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_17_lo[2];
#define niwsn_iovData_17_hi 0
#pragma DATA_SECTION(".niwsn")
static u8 niwsn_iovData_18_lo[2];
#define niwsn_iovData_18_hi 0

EXTERN const u16 niwsn_iovDataFifo[] = {
    (u16)niwsn_iovData_0_lo, (u16)niwsn_iovData_0_hi,
    (u16)niwsn_iovData_1_lo, (u16)niwsn_iovData_1_hi,
    (u16)niwsn_iovData_2_lo, (u16)niwsn_iovData_2_hi,
    (u16)niwsn_iovData_3_lo, (u16)niwsn_iovData_3_hi,
    (u16)niwsn_iovData_4_lo, (u16)niwsn_iovData_4_hi,
    (u16)niwsn_iovData_5_lo, (u16)niwsn_iovData_5_hi,
    (u16)niwsn_iovData_6_lo, (u16)niwsn_iovData_6_hi,
    (u16)niwsn_iovData_7_lo, (u16)niwsn_iovData_7_hi,
    (u16)niwsn_iovData_8_lo, (u16)niwsn_iovData_8_hi,
    (u16)niwsn_iovData_9_lo, (u16)niwsn_iovData_9_hi,
    (u16)niwsn_iovData_10_lo, (u16)niwsn_iovData_10_hi,
    (u16)niwsn_iovData_11_lo, (u16)niwsn_iovData_11_hi,
    (u16)niwsn_iovData_12_lo, (u16)niwsn_iovData_12_hi,
    (u16)niwsn_iovData_13_lo, (u16)niwsn_iovData_13_hi,
    (u16)niwsn_iovData_14_lo, (u16)niwsn_iovData_14_hi,
    (u16)niwsn_iovData_15_lo, (u16)niwsn_iovData_15_hi,
    (u16)niwsn_iovData_16_lo, (u16)niwsn_iovData_16_hi,
    (u16)niwsn_iovData_17_lo, (u16)niwsn_iovData_17_hi,
    (u16)niwsn_iovData_18_lo, (u16)niwsn_iovData_18_hi
};



//=====================================================================
//  Declare the output tokens information
//=====================================================================
EXTERN const u8 niwsn_iovTokenArraySize = 0;

#define niwsn_iovLatchedTokenArray_lo ((u8*)0)
#define niwsn_iovAccumTokenArray_lo ((u8*)0)
EXTERN u8* const niwsn_iovLatchedTokenArray = niwsn_iovLatchedTokenArray_lo;
EXTERN u8* const niwsn_iovAccumTokenArray = niwsn_iovAccumTokenArray_lo;

EXTERN const u8 niwsn_iovTokenIndexArray[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

